version: "3"

services:
  server:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - mongodb
    command: ./zenbot.sh trade --paper
    restart: always

  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles

