version: "3"

services:
  server:
    image: busbyjon/zenbot:latest
    links:
      - mongodb
    command: ./zenbot.sh trade --paper
    restart: always
    networks:
      - zenbotapp


  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles
    networks:
      zenbotapp:
        aliases:
          - mongodb


networks:
    zenbotapp:
