version: "3"

services:
  server:
    build: .
    command: ./zenbot.sh trade --paper
    depends_on: 
      - mongodb
    restart: always
    networks:
      - zenbotapp
    environment:
      - MONGODB_PORT_27017_TCP_ADDR=mongodb
  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles
    networks:
      zenbotapp:
        aliases:
          - mongodb
networks:
    zenbotapp:
